#!/bin/sh

WEBHOOK_URL=

POST_MESSAGE=""
HOST_NAME=`hostname`

if [ -n "$1" ];then
	POST_MESSAGE="$1 "
fi

if [ -n "$SLURM_JOBID" ]; then
	# for SLURM
	POST_MESSAGE="$POST_MESSAGE[JobName:$SLURM_JOB_NAME (JobID:$SLURM_JOBID) @$HOST_NAME]"
elif [ -n "$PBS_JOBID" ]; then
	# for TORQUE
	POST_MESSAGE="$POST_MESSAGE[JobName:$PBS_JOBNAME (JobID:$PBS_JOBID) @$HOST_NAME]"
elif [ -n "$JOB_ID" ]; then
	# for UGE (TSUBAME 3.0)
	POST_MESSAGE="$POST_MESSAGE[JobName:$JOB_NAME (JobID:$JOB_ID) @$HOST_NAME]"
fi

if [ -n "$POST_MESSAGE" ]; then
	curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"$POST_MESSAGE\"}" "$WEBHOOK_URL" > /dev/null 2>&1
fi
