#!/bin/sh

WEBHOOK_URL=

POST_MESSAGE=""

if [[ -n $1 ]];then
	POST_MESSAGE="$1 "
fi

if [[ -n $SLURM_JOBID ]]; then
	# for SLURM
	POST_MESSAGE="$POST_MESSAGE[$SLURM_JOB_NAME - ($SLURM_JOBID) @$SLURM_SUBMIT_HOST]"
elif [[ -n $PBS_JOBID ]]; then
	# for TORQUE
	POST_MESSAGE="$POST_MESSAGE[$PBS_JOBNAME - ($PBS_JOBID) @$PBS_O_HOST]"
elif [[ -n $JOB_ID ]]; then
	# for UGE (TSUBAME 3.0)
	POST_MESSAGE="$POST_MESSAGE[$JOB_NAME - ($JOB_ID) @$SGE_O_HOST]"
fi

if [[ -n $POST_MESSAGE ]]; then
	curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"$POST_MESSAGE\"}" "$WEBHOOK_URL"
fi
